# Generated by Django 5.1.1 on 2024-09-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_remove_ticket_id_ticket_tic_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
