# Generated by Django 5.1.1 on 2024-09-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_ticket_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='userid',
            field=models.CharField(default='0', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='categories',
            name='cat_id',
            field=models.CharField(default='0', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cus_id',
            field=models.CharField(default='0', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tic_id',
            field=models.CharField(default='0', max_length=10, primary_key=True, serialize=False),
        ),
    ]
