# Generated by Django 5.1.1 on 2024-09-10 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_ticket_checked_alter_adminuser_userid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='trxtime',
            field=models.DateField(default=datetime.datetime(2024, 9, 10, 23, 55, 54, 775188)),
            preserve_default=False,
        ),
    ]
