# Generated by Django 5.1.1 on 2024-09-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0007_alter_categories_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='userid',
            field=models.CharField(default='0', max_length=100, primary_key=True, serialize=False),
        ),
    ]
