# Generated by Django 5.1.1 on 2024-09-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0008_alter_adminuser_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='totalcost',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
