# Generated by Django 5.1.1 on 2024-09-10 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0009_ticket_totalcost'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('f_id', models.CharField(default='0', max_length=10, primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=500)),
                ('cus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.customer')),
                ('museum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.categories')),
            ],
        ),
        migrations.CreateModel(
            name='lostandfound',
            fields=[
                ('lnf_id', models.CharField(default='0', max_length=10, primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=500)),
                ('cus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.customer')),
                ('museum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.categories')),
            ],
        ),
    ]
