# Generated by Django 5.1.1 on 2024-09-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0011_lostandfound_telegram_reportfound_telegram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostandfound_telegram',
            name='chat_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lostandfound_telegram',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lostandfound_telegram',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lostandfound_telegram',
            name='message_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lostandfound_telegram',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reportfound_telegram',
            name='chat_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reportfound_telegram',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reportfound_telegram',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reportfound_telegram',
            name='message_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reportfound_telegram',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ticketinfo_telegram',
            name='chat_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ticketinfo_telegram',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ticketinfo_telegram',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ticketinfo_telegram',
            name='message_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ticketinfo_telegram',
            name='place',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ticketinfo_telegram',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
