# Generated by Django 5.1.1 on 2024-09-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0012_alter_lostandfound_telegram_chat_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback_telegram',
            fields=[
                ('f_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('username', models.CharField(max_length=255, null=True)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('chat_id', models.BigIntegerField(null=True)),
                ('message_id', models.BigIntegerField(null=True)),
                ('feedback', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
