# Generated by Django 5.1.1 on 2024-09-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0013_feedback_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback_telegram',
            name='feedback',
            field=models.CharField(max_length=255),
        ),
    ]
